kind: pipeline
type: docker
name: default

clone:
  disable: false

# volumes:
# - name: cache
#   path: /hot-desking-deploy/

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 2m
    script:
      - docker run hello-world

- name: clone and list
  image: alpine/git
  settings:
    username:
      from_secret: DRONE_GIT_USERNAME
    password:
      from_secret: DRONE_GIT_PASSWORD
  commands:
  - git clone https://github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git
  - ls /hot-desking-deploy/

- name: build
  privileged: true
  image: plugins/docker
  volumes:
  - name: cache
    path: /drone/src/hot-desking-deploy/
  - commands:
    - ls
    - cd /hot-desk/
    - chmod 744 setup.sh
    - sh setup.sh
    - bash setup.sh