kind: pipeline
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 2m
    script:
      - docker run hello-world

- name: clone project
  image: alpine/git
  settings:
    username:
      from_secret: DRONE_GIT_USERNAME
    password:
      from_secret: DRONE_GIT_PASSWORD
  commands:
  - pwd
  - ls
  - cd ..
  - pwd
  - ls
  - cd ..
  - pwd
  - ls
  # - git clone https://github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git

- name: Run Bash
  image: appleboy/drone-ssh
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 2m
    script:
    - pwd
    - ls
    - cd ..
    - pwd
    - ls
    - cd ..
    - pwd
    - ls
      # - chmod 744 setup.sh
      # - sh setup.sh
      # - bash setup.sh