kind: pipeline
type: docker
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh

  environment:
    user:
      from_secret: GIT_USERNAME
    pass:
      from_secret: GIT_PASSWORD
    something: some

  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 5m
    envs: [ something ]
    script:
      - id 
      # - chown -R www-data: hot-desking-test
      # - ls
      # - cd hot-desking-test
      # - ls
      # - cd src
      # - ls


      # Set permission to directory used to remove files
      # - sudo chown deploy hot-desking-deploy
      # Terminate all docker containers 
      - docker kill $(docker ps -q)
      # Remove all non-running containers
      - docker system prune -f
      # List all docker containers 
      - docker ps -a
      # TODO CLEAR DIRECTORY TO START FRESH TODO NEED HELP FROM REECE PERMISSION ISSUE WHEN TRYING TO DELETE LEFT OVER FILES FROM NODE MODULES
      # - rm -rf hot-desking-deploy
      # Clone Directory
      - git clone -b merge-projects-test https://DamynFilipuzzi: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@github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git hot-desking-test1/
      - ls
      # change directories 
      - cd hot-desking-test1/
      # ensure all containers have been stopped
      - docker compose down
      # Run Bash File to setup project
      - chmod 744 setup.sh
      - sh setup.sh


      # - echo $something
      # - echo $${something}
      # - echo $user
      # - echo $${user}

      # - git clone -b merge-projects-test https://$${GIT_USERNAME}:$${GIT_PASSWORD}@github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git hot-desking/
      # - ls