kind: pipeline
type: docker
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 2m
    script:
      - docker run hello-world

steps:
- name: test
  image: compose:1.29.2
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - up -f /drone/src/docker-compose.yaml
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

- name: clone and run project
  image: alpine/git
  settings:
    username:
      from_secret: DRONE_GIT_USERNAME
    password:
      from_secret: DRONE_GIT_PASSWORD
  commands:
  # - git clone https://github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git
  - chmod 744 setup.sh
  - sh setup.sh
  - bash setup.sh