kind: pipeline
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 2m
    script:
      - docker run hello-world

- name: clone project
  image: alpine/git
  settings:
    username:
      from_secret: DRONE_GIT_USERNAME
    password:
      from_secret: DRONE_GIT_PASSWORD
  commands:
  - git clone https://github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git
  - bash setup.sh
  # - git checkout $DRONE_COMMIT
