kind: pipeline
type: docker
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh

  environment:
    USER:
      from_secret: GIT_USERNAME
    PASS:
      from_secret: GIT_PASSWORD
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 5m
    envs: [ PASS, USER ]
    script:
      ################################# Test #################################
      - ls
      - docker run -v "$(pwd):/src" -it alpine /bin/sh -c "rm -rf /src/* && rm -rf /src/.*”
      - ls
      - cd ..
      - ls

      ################################# Pull fresh github #################################
      # - ls
      # # Set permission to directory used to remove files
      # # - sudo chown deploy hot-desking-deploy
      # # Terminate all docker containers 
      # - docker kill $(docker ps -q)
      # # Remove all non-running containers
      # - docker system prune -f
      # # List all docker containers 
      # - docker ps -a
      # # TODO CLEAR DIRECTORY TO START FRESH TODO NEED HELP FROM REECE PERMISSION ISSUE WHEN TRYING TO DELETE LEFT OVER FILES FROM NODE MODULES
      # # - rm -rf hot-desking-deploy
      # # Clone Directory
      # - git clone -b main https://$${USER}:$${PASS}@github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git test-pull8/
      # - ls
      # # change directories 
      # - cd test-pull8/
      # # Run Bash File to setup project
      # - chmod 744 setup.sh
      # - sh setup.sh

      # - docker compose run --rm artisan schedule:list
      # - echo Server is LIVE

      # ################################# Pull new changes #################################
      # # Terminate all docker containers 
      # - docker kill $(docker ps -q)
      # # Remove all non-running containers
      # - docker system prune -f
      # # List all docker containers 
      # - docker ps -a
      # # change directories
      # - cd test-pull5/
      # - pwd
      # # fetch new changes Directory
      # - git fetch
      # - git pull
      # # Run Bash File to setup project
      # - chmod 744 run.sh
      # - sh run.sh

      # - docker compose run --rm artisan schedule:list
      # - echo Server is LIVE

trigger:
  branch:
  - main
  event:
  - push
  status:
  - success