kind: pipeline
type: docker
name: default

clone:
  disable: true

# volumes:
# - name: cache
#   path: /drone/src/
volumes:
- name: dockersock
  temp: {}
  
workspace:
  path: /home/deploy

services:
- name: docker
  image: docker:dind
  # privileged: true
  volumes:
  - name: dockersock
    path: /var/run

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 2m
    script:
      # - docker version
      - pwd
      - ls
      # - docker run hello-world

- name: clone and list
  image: alpine/git
  settings:
    username:
      from_secret: DRONE_GIT_USERNAME
    password:
      from_secret: DRONE_GIT_PASSWORD
  commands:
  - git clone -b merge-projects-test https://github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git
  - pwd
  - ls
  # - docker version
  # - chmod 744 setup.sh
  # - sh setup.sh
  # - bash setup.sh

- name: build
  image: docker:dind
  commands:
    - ls
    - cd hot-desking-deploy/
    - ls
    - chmod 744 setup.sh
    - sh setup.sh
    # - bash setup.sh