kind: pipeline
name: default

# steps:
# - name: ssh
#   image: appleboy/drone-ssh
#   settings:
#     host:
#       - s291.ok.ubc.ca
#     username: deploy
#     key:
#       from_secret: DEPLOY_SSH_KEY
#     port: 22
#     command_timeout: 2m
#     script:
#       - docker run hello-world

- name: clone project
  image: alpine/git
  settings:
    username:
      from_secret: DRONE_GIT_USERNAME
    password:
      from_secret: DRONE_GIT_PASSWORD
  commands:
  - git clone https://github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git
  # - cp docker-compose.example.yml docker-compose.yml
  # - ls
  # - cd src/
  # - cp .env.example .env
  # - ls
  # - cd ..
  # - docker-compose up -d --build site
  # - docker-compose run --rm composer update
  # - docker-compose run --rm npm install
  # - docker-compose run --rm npm run dev
  # - docker-compose run --rm artisan migrate:refresh
  # - docker-compose run --rm artisan db:seed --class=ResourceSeeder
  # - docker-compose run --rm artisan db:seed --class=UserSeeder

- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 2m
    script:
      # - docker run hello-world
      - ls
      # - chmod 744 setup.sh
      # - sh setup.sh
      # - bash setup.sh
