kind: pipeline
type: docker
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh

  environment:
    USER:
      from_secret: GIT_USERNAME
    PASS:
      from_secret: GIT_PASSWORD
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 5m
    envs: [ PASS, USER ]
    script:
      # Pull latest changes to the runner
      - cd runner
      - git stash
      - git fetch
      - git pull
      # run the runner bash script
      - chmod 744 runner.sh
      - sh runner.sh $${USER} $${PASS}


      ################################# Test #################################
      # - docker run -v "$(pwd):/src" -it alpine /bin/sh -c "rm -rf /src/* && rm -rf /src/.*"
      # - ls
      # - docker run -v "$(pwd):/src" -it alpine /bin/sh -c "rm -rf /hot-desk/* && rm -rf /hot-desk/.*"

trigger:
  branch:
  - main
  event:
  - push
  status:
  - success