kind: pipeline
type: docker
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  environment:
    git_user:
      from_secret: GIT_USERNAME
    git_pass:
      from_secret: GIT_PASSWORD
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 5m
    envs: [git_user]
    script:
      # - rm -rf hot-desking-deploy
      # - git clone -b merge-projects-test https://DamynFilipuzzi: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@github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git hot-desk/
      - echo somthing
      - echo $git_user
      - echo $${git_user}
      # - git clone -b merge-projects-test https://$${GIT_USERNAME}:$${GIT_PASSWORD}@github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git hot-desking/
      # - ls

      # - cd hot-desk
      # - docker compose down
      # - chmod 744 setup.sh
      # - sh setup.sh

# - name: clone and list
#   image: alpine/git
#   settings:
#     username:
#       from_secret: DRONE_GIT_USERNAME
#     password:
#       from_secret: DRONE_GIT_PASSWORD
#   commands:
#   - git clone -b merge-projects-test https://github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git
#   - pwd

# - name: build
#   image: docker
#   volumes:
#   - name: dockersock
#     path: /var/run/docker.sock
#   commands:
#     - pwd
#     - ls
#     - cd ..
#     - pwd
#     - ls
#     - cd ..
#     - pwd
#     - ls
#     - cd var
#     - ls
#     - cd run
#     - ls docker.sock
    # - cd hot-desking-deploy/
    # - ls
    # - chmod 744 setup.sh
    # - sh setup.sh