kind: pipeline
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - s291.ok.ubc.ca
    username: deploy
    key:
      from_secret: DEPLOY_SSH_KEY
    port: 22
    command_timeout: 2m
    script:
      - git clone https://github.com/UBCO-COSC-499-Summer-2022/hot-desking-deploy.git
      - cd hot-desking-deploy/
      - bash setup.sh