name: Build

on:
  push:
#     branches: [ "main", "testing-and-staging"]
#   pull_request:
#     branches: [ "main", "testing-and-staging"]
    branches: []
  pull_request:
    branches: []
    
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
        coverage: xdebug
    - uses: actions/checkout@v3
    - name: Copy .env
      working-directory: ./src
      run: php -r "copy('.env.testing', '.env');"
    - name: Install Dependencies
      working-directory: ./src
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      working-directory: ./src
      run: php artisan key:generate
    - name: Directory Permissions
      working-directory: ./src
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      working-directory: ./src
      run: |
        mkdir -p database
        touch database/database.pgsql
    - name: Run Migrations
      working-directory: ./src
      run: php artisan migrate
    - name: (Unit and Feature tests) via PHPUnit
      working-directory: ./src
      run: php artisan test
    - name: (Coverage Test) via PHPUnit
      working-directory: ./src
      run: vendor/bin/phpunit --coverage-text
